# -*- coding: utf-8 -*-
"""expense_tracker.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NLe6Rw5ufI7wqSMjJpj2g3Mgag4mwKzm

# 📊 Expense Tracker :
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

df=pd.read_csv("/content/expenses.csv")
df.head()

df.info()

df.isnull().sum()

df.dropna(inplace=True)
df

for i in range(len(df)):
  if df["Amount"].iloc[i] <= 0:
    print("Invalid amount found at row :", i)

# Invalid Amount filled with 0
df.loc[df["Amount"] <= 0, "Amount"] = 0
df

class ExpenseTracker:
    def __init__(self):
        self.expenses = []
    def add_expense(self, date, amount, category, description):
        self.expenses.append({
            "Date": date,
            "Amount": amount,
            "Category": category,
            "Description": description
        })
    def get_summary(self):
        df = pd.DataFrame(self.expenses)
        amounts = df["Amount"].values
        total = np.sum(amounts)
        average = np.mean(amounts)
        print("Total Spending:", total)
        print("Average Spending:", average)
        print("\nCategory-wise Spending:")
        categories = df["Category"].unique()
        for cat in categories:
            cat_amounts = df[df["Category"] == cat]["Amount"].values
            cat_total = np.sum(cat_amounts)
            print(cat, ":", cat_total)
    def filter_expenses(self, category):
        df = pd.DataFrame(self.expenses)
        filtered = df[df["Category"] == category]
        print("\nFiltered Expenses (" + category + "):")
        print(filtered)
    def generate_report(self):
        df = pd.DataFrame(self.expenses)
        print("\nExpense Report:")
        print(df)

# Get summary
tracker = ExpenseTracker()
for index, row in df.iterrows():
    tracker.add_expense(
        row["Date"],
        row["Amount"],
        row["Category"],
        row["Description"]
    )
tracker.get_summary()

# Filtering expenses
tracker.filter_expenses("Food")

# Generating reports
tracker.generate_report()

# Using pandas to group expenses by category
category_group=df.groupby("Category")["Amount"].sum()
print("Total Expense per category :")
print(category_group)

# Identifying top spending categories by pandas :
top_categories=category_group.nlargest(3)
print("\nTop 3 spending categories :")
print(top_categories)

# Identifying top spending periods by pandas :
top_month_id=top_month.idxmax()
top_month_value=top_month.max()
print("Top spending month :", top_month_id)
print("Top spending month value :", top_month_value)

# Bar chart - Total expenses by category
category_sum=df.groupby("Category")["Amount"].sum()
plt.figure(figsize=(8, 6))
category_sum.plot(kind="bar", label="Total Expense")
plt.xlabel("Category", fontsize=16, fontweight="bold")
plt.ylabel("Amount spent", fontsize=16, fontweight="bold")
plt.title("Total Expenses by Category", fontsize=16, fontweight="bold")
plt.legend()
plt.show()

# Line chart - Spending trends over time
date_sum=df.groupby("Date")["Amount"].sum()
plt.figure(figsize=(12,6))
date_sum.plot(label="Daily Spending", marker="o")
plt.xlabel("Date", fontsize=16, fontweight="bold")
plt.ylabel("Amount spent", fontsize=16, fontweight="bold")
plt.title("Spending Trends Over Time", fontsize=16, fontweight="bold")
plt.legend()
plt.show()

# Pie chart - Proportional spending distribution by category
plt.figure(figsize=(8, 8))
category_sum.plot(kind="pie", autopct="%1.1f%%")
plt.title("Proportional Spending Distribution by Category", fontsize=16, fontweight="bold")
plt.legend(category_sum.index)
plt.ylabel("")
plt.show()

# Histogram - Frequency of expense amounts
plt.figure(figsize=(10,6))
plt.hist(df["Amount"], label= "Expense Frequency")
plt.title("Frequency of Expense Amounts", fontsize=16, fontweight="bold")
plt.xlabel("Amount", fontsize=16, fontweight="bold")
plt.ylabel("Frequency", fontsize=16, fontweight="bold")
plt.legend()
plt.show()